apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: excalidraw-app
  namespace: istio-ingress
spec:
  secretName: excalidraw-app
  commonName: kanadon-test.ddns.net
  dnsNames:
  - kanadon-test.ddns.net
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
